# Translation Checker 配置文件

# 数据处理配置
data:
  # 支持的文件格式
  supported_formats: ['.xlsx', '.xls', '.csv']
  # 默认编码
  encoding: 'utf-8'
  # Excel列名映射 - 可以根据你的文件格式自定义
  column_mapping:
    id: ['ID', 'id', 'Index', 'index', '序号', '编号', '条目ID']  # 添加你的ID列名
    source: ['简体', '中文', 'source', '源文本', '原文']      # 添加你的源语言列名
    target: ['英语', 'EN', 'target', '翻译', '译文', '目标文本']  # 添加你的目标语言列名

# 检测层配置
detection:
  # 基础规则检测
  rules:
    # 长度比例检查 (目标文本长度/源文本长度的合理范围)
    length_ratio_min: 0.3
    length_ratio_max: 3.0
    # 空值检查
    check_empty: true
    # 特殊字符检查
    check_special_chars: true
    
  # 语义相似度检测
  similarity:
    # 使用的模型 - 可选择不同的模型以平衡速度和精度
    model_name: 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'
    # 相似度阈值 (低于此值认为翻译可能有问题) - 可根据需要调整 0.6-0.8
    threshold: 0.7
    # 批处理大小 - 根据内存情况调整，内存不足可改为16或8
    batch_size: 32
    
  # 关键词规范性检测
  keywords:
    # 关键词字典文件路径
    dictionary_path: 'config/keywords.yaml'
    # 是否区分大小写
    case_sensitive: false
    # 是否检查专业术语一致性
    check_terminology: true

# LLM配置
llm:
  # 使用的LLM提供商 (openai, ollama, qwen, glm, wenxin)
  provider: 'ollama'  # 默认使用免费的Ollama
  
  # OpenAI配置 (付费)
  openai:
    model: 'gpt-3.5-turbo'
    api_key: ''  # 请在环境变量中设置 OPENAI_API_KEY
    max_tokens: 1000
    temperature: 0.1
    
  # Ollama本地模型配置 (免费推荐)
  ollama:
    model: 'qwen2.5:14b-instruct'  # 推荐：14B指令优化版，翻译质量更高
    # model: 'qwen2.5:7b'          # 备选：7B版本，内存需求更低
    # model: 'qwen2.5:32b-instruct' # 备选：32B版本，最佳质量（需要更多内存）
    base_url: 'http://localhost:11434'
    max_tokens: 1000
    temperature: 0.1
    
  # 通义千问API配置 (免费额度)
  qwen:
    model: 'qwen-turbo'
    api_key: ''  # 请在环境变量中设置 DASHSCOPE_API_KEY
    max_tokens: 1000
    temperature: 0.1
    
  # 智谱AI GLM配置 (免费额度)
  glm:
    model: 'glm-4-flash'
    api_key: ''  # 请在环境变量中设置 GLM_API_KEY
    max_tokens: 1000
    temperature: 0.1
    
  # 百度文心一言配置 (免费额度)
  wenxin:
    model: 'ernie-3.5-turbo'
    api_key: ''  # 请在环境变量中设置 WENXIN_API_KEY
    secret_key: ''  # 请在环境变量中设置 WENXIN_SECRET_KEY
    max_tokens: 1000
    temperature: 0.1
  # 评估提示词模板
  prompt_template: |
    评估翻译质量并返回JSON格式结果。
    
    原文：{source}
    译文：{target}
    
    要求：
    1. 准确性(accuracy)：翻译准确性(1-10分)
    2. 流畅性(fluency)：语言流畅性(1-10分)  
    3. 一致性(consistency)：术语一致性(1-10分)
    4. 完整性(completeness)：内容完整性(1-10分)
    
    **重要：必须严格按照以下JSON格式返回，不要添加任何解释文字：**
    
    {{
        "score": 8,
        "accuracy": 8,
        "fluency": 7,
        "consistency": 9,
        "completeness": 8,
        "issues": ["问题描述"],
        "suggestions": ["改进建议"],
        "explanation": "简要说明"
    }}
    
    只返回JSON，不要其他内容。

# 输出配置
output:
  # 报告格式 (excel, json, html)
  format: 'excel'
  # 输出目录
  output_dir: 'output'
  # 是否包含详细分析
  include_details: true
  # 是否生成可视化图表
  generate_charts: true

# 日志配置
logging:
  level: 'DEBUG'  # DEBUG, INFO, WARNING, ERROR - 启用详细调试
  file: 'logs/translation_checker.log'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
