# 关键词和术语字典
# 用于检查翻译中关键词的一致性和规范性

# 专业术语映射配置
terminology:
  # 术语来源类型: 'file' 或 'inline'
  source_type: 'file'
  # Excel文件路径 (相对于项目根目录)
  excel_file: 'data/terminology.xlsx'
  # Excel工作表名称
  sheet_name: 'terminology'
  # 列名配置
  columns:
    chinese: '中文术语'      # 中文术语列名
    english: '英文术语'      # 英文术语列名  
    alternatives: '备选翻译'  # 备选翻译列名(可选)
  
  # 内联术语定义 (当source_type为'inline'时使用)
  inline_terms:
    "人工智能": ["artificial intelligence", "AI"]
    "机器学习": ["machine learning", "ML"]

# 品牌名称 (必须保持一致)
brands:
  - "Microsoft"
  - "Google"
  - "Apple"
  - "Amazon"
  - "Facebook"
  - "OpenAI"
  - "GitHub"

# 禁用词汇 (不应出现在翻译中)
forbidden_words:
  - "机翻"
  - "谷歌翻译"
  - "百度翻译"
  - "[翻译]"
  - "[译]"

# 格式规范
format_rules:
  # 数字格式
  numbers:
    # 是否保持原文数字格式
    preserve_format: true
    # 千位分隔符规范
    thousand_separator: ","
  
  # 标点符号
  punctuation:
    # 英文标点规范
    use_english_punctuation: true
    # 引号规范
    quote_style: "double"  # single, double
  
  # 大小写规范
  capitalization:
    # 专有名词首字母大写
    proper_nouns: true
    # 句首大写
    sentence_start: true

# 上下文相关规则
context_rules:
  # 技术文档
  technical:
    # 保持技术术语英文原文
    keep_original_terms: true
    # 添加中文解释
    add_chinese_explanation: false
  
  # 营销文案
  marketing:
    # 使用本土化表达
    localize_expressions: true
    # 保持品牌调性
    maintain_brand_tone: true
